---
title: "STAT4011_pj1_korea"
output: html_document
---

data source : https://www.kaggle.com/kimjihoo/coronavirusdataset

possible use dataset
policy, searchtrend, TimeProvince


load the required library
```{r}
library(ggplot2)
```

set seed and read data
```{r}
set.seed(4011)
file_path = "C:/Users/cheng/OneDrive/Desktop/hw/STAT4011/STAT4011/dataset"
case =  read.csv(paste0(file_path, '/Time.csv'))
policy = read.csv(paste0(file_path, '/Policy.csv'))
search_trend = read.csv(paste0(file_path, '/SearchTrend.csv'))
province = read.csv(paste0(file_path, '/TimeProvince.csv'), stringsAsFactors = FALSE)
weather = read.csv(paste0(file_path, '/Weather.csv'), stringsAsFactors = FALSE)
```


merge and plot for csae, policy and search trend
```{r, fig.width = 8, fig.height = 5}
case_policy_df = merge(case, policy, by.x='date', by.y='start_date', all = TRUE)[-1,]
case_policy_search = merge(case_policy_df, search_trend, by.x='date', by.y='date')
df = case_policy_search
df$policy_id = as.numeric(df$policy_id)
df$date = as.Date(df$date)
for (i in 1:nrow(df)){
  if (is.na(df$policy_id[i])) df$policy_id[i] = 0
  if(df$policy_id[i] > 0) {
    df$policy_id[i] = 1
  } else {
    df$policy_id[i] = 0
  }
}
#plot the graph
ggplot() + 
geom_line(data = df, aes(x = date, y = confirmed, color = 'confirmed')) + 
geom_line(data = df, aes(x = date, y = released, color = 'released'))+ 
geom_point(data = df, aes(x = date, y = policy_id, color = 'government applied policy'), size = 0.01) +
ylab('')
# plot search trend
ggplot() +
geom_line(data = df, aes(x = date, y = coronavirus, color = 'ppl search for coronavirus'))

ggplot() +
geom_line(data = df, aes(x = date, y = flu, color = 'ppl search for flu'))
```
correlation 
```{r}
corr_df = as.data.frame(cbind(df$confirmed, df$coronavirus, df$flu, df$policy_id))
colnames(corr_df) = c('confirmed', 'keyword_covid19', 'keyword_flu', 'gov_policy')
corr = cor(corr_df)
```


split the rows of TimeProvince
```{r}
province$province = as.factor(province$province)
province_list = split(province, province$province)
province_df = as.data.frame(province_list)

pro_df = cbind(province_df$Busan.date, 
province_df$Busan.confirmed, 
province_df$Chungcheongbuk.do.confirmed, 
province_df$Chungcheongnam.do.confirmed,
province_df$Daegu.confirmed,
province_df$Daejeon.confirmed,
province_df$Gangwon.do.confirmed,
province_df$Gwangju.confirmed,
province_df$Gyeonggi.do.confirmed,
province_df$Gyeongsangbuk.do.confirmed,
province_df$Gyeongsangnam.do.confirmed,
province_df$Incheon.confirmed,
province_df$Jeju.do.confirmed,
province_df$Jeollabuk.do.confirmed,
province_df$Jeollanam.do.confirmed,
province_df$Sejong.confirmed,
province_df$Seoul.confirmed,
province_df$Ulsan.confirmed)

temp = as.data.frame(apply(pro_df[,2:ncol(pro_df)], 2, as.numeric))
colnames(temp) = c('Busan', 'Chungcheongbuk', 'Chungcheongnam', 'Daegu', 'Daejeon', 'Gangwon','Gwangju', 'Gyeonggi', 'Gyeongsangbuk', 'Gyeongsangnam', 'Incheon', 'Jeju', 'Jeollabuk', 'Jeollanam', 'Sejong', 'Seoul', 'Ulsan')
pro_df = data.frame(province_df$Busan.date, temp)
colnames(pro_df)[1] = 'date'
#convert datetime
pro_df[,1] = anytime::anydate(pro_df[,1])
```

standardize it by min-max scales
```{r}
normalize <- function(x)
{
    return((x- min(x)) /(max(x)-min(x)))
}
pro_stand_df = apply(pro_df[,2:ncol(pro_df)], 2, normalize)
pro_stand_df = data.frame(pro_df[,1], pro_stand_df)
pro_stand_df[,1] = anytime::anydate(pro_stand_df[,1])
colnames(pro_stand_df)[1] = 'date'
```

plot TimeProvince
```{r, fig.width = 8, fig.height = 8}
df = pro_stand_df
ggplot() + 
geom_line(data = df, aes(x = date, y = Busan, color = 'Busan')) + 
geom_line(data = df, aes(x = date, y = Chungcheongbuk, color = 'Chungcheongbuk'))+ 
geom_line(data = df, aes(x = date, y = Chungcheongnam, color = 'Chungcheongnam'))+
geom_line(data = df, aes(x = date, y = Daegu, color = 'Daegu'))+
geom_line(data = df, aes(x = date, y = Daejeon, color = 'Daejeon'))+
geom_line(data = df, aes(x = date, y = Gangwon, color = 'Gangwon'))+
geom_line(data = df, aes(x = date, y = Gwangju, color = 'Gwangju'))+
geom_line(data = df, aes(x = date, y = Gyeonggi, color = 'Gyeonggi'))+
geom_line(data = df, aes(x = date, y = Gyeongsangbuk, color = 'Gyeongsangbuk'))+
geom_line(data = df, aes(x = date, y = Gyeongsangnam, color = 'Gyeongsangnam'))+
geom_line(data = df, aes(x = date, y = Incheon, color = 'Incheon'))+
geom_line(data = df, aes(x = date, y = Jeju, color = 'Jeju'))+
geom_line(data = df, aes(x = date, y = Jeollabuk, color = 'Jeollabuk'))+
geom_line(data = df, aes(x = date, y = Jeollanam, color = 'Jeollanam'))+
geom_line(data = df, aes(x = date, y = Sejong, color = 'Sejong'))+
geom_line(data = df, aes(x = date, y = Seoul, color = 'Seoul'))+
geom_line(data = df, aes(x = date, y = Ulsan, color = 'Jeollabuk'))+

ylab('')
```

find the correlation of the interesting factor
(move the place)
```{r}

corr_pro = cor(pro_df[,2:ncol(pro_df)])
```

